name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.1.9
        run_install: true
    - name: Prettier check
      run: pnpx prettier --check *.ts
    - name: Run tests
      run: pnpm test
  user_test:
    name: User Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ./g-plane/typed-query-selector
    - name: Checkout "refined-github"
      uses: actions/checkout@v3
      with:
        repository: sindresorhus/refined-github
        ref: 60ac04e85cdb0c597e90d3d314ad6fb4c1fe4d8d
        path: ./sindresorhus/refined-github
    - name: Install dependencies
      run: npm ci
      working-directory: ./sindresorhus/refined-github
    - name: Link package
      run: |
        cd ./g-plane/typed-query-selector
        sudo npm link
        cd ../../sindresorhus/refined-github
        npm link typed-query-selector
    - name: Execute in non-strict mode
      run: node node_modules/.bin/tsc --noEmit --extendedDiagnostics
      working-directory: ./sindresorhus/refined-github
    - name: Execute in strict mode
      run: |
        sed -i "s/typed-query-selector/typed-query-selector\/strict/" source/refined-github.ts
        node node_modules/.bin/tsc --noEmit --extendedDiagnostics
      working-directory: ./sindresorhus/refined-github
